### ISSUE TITLE
How to Register - Considerations -Incorrect Link

### ISSUE THREAD

**Issue by nickbeau** [lindabeau70/Ccfc#22]
The Link to Fees and Requirements goes to curlcurlyouthclub

![image](https://github.com/lindabeau70/Ccfc/assets/4262496/dc9f8af2-eff4-4363-adf8-a4ea748fa2bf)

**Comment by lindabeau70** [comment]
When I went in to edit - it seemed to have the right link.  But I re-saved and it seems to work now.
