### ISSUE TITLE
Contacts Page - Box at the bottom has twitter and linkedin (we don't have those)

### ISSUE THREAD

**Issue by nickbeau** [lindabeau70/Ccfc#27]
![image](https://github.com/lindabeau70/Ccfc/assets/4262496/73228c10-d45c-468b-8344-f1f41ced1f12)

**Comment by nickbeau** [comment]
They now need to be centered: 
![image](https://github.com/lindabeau70/Ccfc/assets/4262496/25128e16-1b3d-42d5-a82e-427b5c92afe7)

**Comment by lindabeau70** [comment]
centred
